name: Notify Old PRs
description: A custom action to notify about PRs older than 7 days.
inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
  github_repository:
    description: "Github repository path e.g. 'AlmSmartDoctor/SmartDoctorCrm'"
  slack_bot_token:
    description: "Slack bot token for notifications"
    required: true
  repo_slack_channel_map:
    description: "A dictionary-like string mapping repository names to their corresponding Slack channel IDs."
    required: true
runs:
  using: "composite"
  steps:
    - run: python scripts/notify_old_prs.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{inputs.github_repository}}
        SLACK_BOT_TOKEN: ${{ inputs.slack_bot_token }}
        REPO_SLACK_CHANNEL_MAP: ${{ inputs.repo_slack_channel_map }}